### ISSUE TITLE
Updating `pipes-tar` to use `FreeT`?

### ISSUE THREAD

**Issue by Gabriella439** [ocharles/pipes-tar#2] opened 2013-08-26 19:29 UTC
Would you be interested in me submitting a pull request to update `pipes-tar` to use the `FreeT` idioms I mentioned before on the mailing list?

What I had in mind was something like this (the names I'm picking are arbitrary, just focus on the types):

``` haskell
data TarEntry x = TarEntry TarHeader (Producer ByteString m x)

instance Functor TarEntry where ...

fromTar :: (Monad m) => Producer ByteString m () -> FreeT TarEntry m ()

toTar :: (Monad m) => FreeT TarEntry m () -> Producer ByteString m ()
```

The idea is that the user would use `fromTar` to split the raw stream into a sequence of nested `TarEntry`s, and then apply transformations to that `FreeT` and they could even optionally convert back to a raw byte stream again using `toTar` when they are done (which is useful if they just wanted to modify the tar stream).

In your specific use case, you would still use something like `iterT` or `runFreeT` to loop over the `FreeT` and run a pipeline on each individual `Producer` in the list like you mentioned before.

**Comment by ocharles** [comment] 2013-08-26 21:32
I've actually already done that work but couldn't find a safe enough way to
consume FreeT. I'm at my partners house at the moment, but I'll try and
remember to share what I have when I get home.

Thanks!

**Comment by ocharles** [comment] 2013-08-27 23:18
It took a little longer than expected to get this working since the Iso
implementation, but I've updated master to use FreeT parsing. It's
messy, and probably not very idiomatic - but it seems to be doing the
job as far as parsing tar files!

Feedback still happily taken :)

Also, just a heads up - I've confirmed a pipes talk for Sept 18th, and
am just finishing putting my deck together for it. I'll share the repo
with you once I'm done and happy with the content, and then we can
refine it.
- ollie

**Comment by Gabriella439** [comment] 2013-08-27 23:28
I'm jealous!  I wish people would invite me to give `pipes` talks.  :)

I skimmed your internals and they looked fine to me and the public-facing API of `parseTarEntries` is pretty much spot on, although you probably want to re-export `TarEntry` and `TarHeader`, too.

Don't forget to include some analog of `toTar` so that users can also build their own tar files, too, or I can write it up for you if you want.

**Comment by ocharles** [comment] 2013-08-27 23:29
All planned, notice the gigantic block of commented code later ;-)

**Comment by Gabriella439** [comment] 2013-08-27 23:29
Oh, you're right!  I mistakenly thought that was a really extensive tutorial.  :)

**Comment by ocharles** [comment] 2017-02-07 11:04
Closing issues here now that [`tar-conduit`](http://hackage.haskell.org/package/tar-conduit) is out. I no longer need this project, so it's unlikely to see the light of day any time soon.

**Closed as completed by ocharles** 2017-02-07 11:04 UTC
